CypherShop/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace CypherShop.Models
{
    public class Cart
    {
        //public SANPHAM SanPham { get; set; }
        //public int Quantity { get; set; }
        CypherShopEntities db = new CypherShopEntities();
        public int iMaSP { get; set; }
        public string sTenSP { get; set; }
        public string sAnhbia { get; set; }
        public double dDongia { get; set; }
        public int iSoluong { get; set; }
        public double dThanhtien
        {
            get { return iSoluong * dDongia; }
        }
        //Khởi tạo giỏ hàng theo mã sách được truyền vào (Mặc định là 1)
        public Cart(int MaSP)
        {
            iMaSP = MaSP;
            SANPHAM sp = db.SANPHAMs.Single(n => n.MaSP == iMaSP);
            sTenSP = sp.TenSP;
            sAnhbia = sp.Anhbia;
            dDongia = double.Parse(sp.Giaban.ToString());
            iSoluong = 1;

        }
    }
}

CypherShop/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CypherShop.Models
{
    public class Order
    {
        public List<PHUONGTHUCTHANHTOAN> ListPTTH { get; set; }
        public List<SANPHAM> ListSanPham { get; set; }
    }
}

CypherShop/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CypherShop.Models;
namespace WebsiteBanHang.Controllers
{
    public class CartController : Controller
    {
        CypherShopEntities db = new CypherShopEntities();
        // GET: Cart

        public List<Cart> Laygiohang()
        {
            List<Cart> listGiohang = Session["Cart"] as List<Cart>;
            if (listGiohang == null)
            {
                listGiohang = new List<Cart>();
                Session["Cart"] = listGiohang;
            }
            return listGiohang;
        }
        public ActionResult ThemGioHang(int iMaSP, string strURL)
        {
            List<Cart> listGioHang = Laygiohang();
            Cart sanpham = listGioHang.Find(n => n.iMaSP == iMaSP);
            if (sanpham == null)
            {
                sanpham = new Cart(iMaSP);
                listGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoluong++;
                return Redirect(strURL);
            }

        }
        //phương thức tính tổng số lượng
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<Cart> listGiohang = Session["Cart"] as List<Cart>;
            if (listGiohang != null)
            {
                iTongSoLuong = listGiohang.Sum(n => n.iSoluong);
            }
            return iTongSoLuong;
        }
        //phuong thức tính tổng tiền
        private double TongTien()
        {
            double iTongTien = 0;
            List<Cart> listGiohang = Session["Cart"] as List<Cart>;
            if (listGiohang != null)
            {
                iTongTien = listGiohang.Sum(n => n.dThanhtien);
            }
            return iTongTien;
        }
        // Phương thức hiển thị xử lí giỏ hàng
        public ActionResult Giohang()
        {
            List<Cart> listGiohang = Laygiohang();
            if (listGiohang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.TongSoluong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return View(listGiohang);

        }

        // GET: Giohang
        public ActionResult GiohangPartial()
        {
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        //xoá giỏ hàng
        public ActionResult XoaGioHang(int iMasp)
        {
            List<Cart> listGiohang = Laygiohang();

            Cart sanpham = listGiohang.SingleOrDefault(n => n.iMaSP == iMasp);
            if (sanpham != null)
            {
                listGiohang.RemoveAll(n => n.iMaSP == iMasp);
                return RedirectToAction("Giohang");

            }
            if (listGiohang.Count == 0)
            {
                return RedirectToAction("Index", "Books");
            }
            return RedirectToAction("Giohang");
        }
        //cap nhật giỏ hàng
        public ActionResult CapNhatGioHang(int iMaSp, FormCollection f)
        {
            List<Cart> listGiohang = Laygiohang();
            Cart sanpham = listGiohang.SingleOrDefault(n => n.iMaSP == iMaSp);
            if (sanpham != null)
            {
                sanpham.iSoluong = int.Parse(f["txtsoluong"].ToString());
            }
            return RedirectToAction("Giohang");
        }
        //xoa tat ca gio hang
        public ActionResult XoaTatCaGioHang()
        {
            // lấy giỏ hàng từ session
            List<Cart> listGiohang = Laygiohang();
            listGiohang.Clear();
            return RedirectToAction("Index", "Home");
        }
        [HttpGet]
        public ActionResult Order()
        {
            //Kt đăng nhập
            if (Session["user"] == null || Session["user"].ToString() == "")
            {
                return RedirectToAction("Login", "Home");
            }    
            if(Session["Cart"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.MaPhuongThuc = new SelectList(db.PHUONGTHUCTHANHTOANs.ToList().OrderBy(n => n.MaPhuongThuc), "MaPhuongThuc", "TenPhuongThuc");
            // Lấy giỏ hàng tử Session
            List<Cart> lstCart = Laygiohang();
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return View(lstCart);
        }
        public ActionResult Order(FormCollection collection, DONDATHANG ddh)
        {
            ViewBag.MaPhuongThuc = new SelectList(db.PHUONGTHUCTHANHTOANs.ToList().OrderBy(n => n.MaPhuongThuc), "MaPhuongThuc", "TenPhuongThuc");
            //Them don hang
            //DONDATHANG ddh = new DONDATHANG();
            KHACHHANG kh = (KHACHHANG)Session["users"];
            List<Cart> gh = Laygiohang();
            ddh.MaKH = kh.MaKH;
            ddh.Ngaydat = DateTime.Now;
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["Ngaygiao"]);
            ddh.Ngaygiao = DateTime.Parse(ngaygiao);   
            ddh.Tinhtranggiaohang = false;
            ddh.Dathanhtoan = false;
            ddh.Trangthai = true;
            db.DONDATHANGs.Add(ddh);


            db.SaveChanges();
            //Them chi tiet don hang
            foreach (var item in gh)
            {
                CHITIETDONTHANG ctdh = new CHITIETDONTHANG();
                ctdh.MaDonHang = ddh.MaDonHang;
                ctdh.MaSP = item.iMaSP;
                ctdh.Soluong = item.iSoluong;
                ctdh.Dongia = (decimal)item.dDongia;
                db.CHITIETDONTHANGs.Add(ctdh);
            }
            db.SaveChanges();
            Session["Cart"] = null;
            return RedirectToAction("Xacnhandonhang", "Cart");
        }
        public ActionResult Xacnhandonhang()
        {
            return View();
        }
        
    }

}

CypherShop/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CypherShop.Models;

namespace CypherShop.Controllers
{
    public class DetailController : Controller
    {
        CypherShopEntities db = new CypherShopEntities();
        // GET: Detail
        public ActionResult Index(int Id, int nsx)
        {
            // lấy thông tin sản phẩm theo id
            var objSanPham = db.SANPHAMs.Where(n => n.MaSP == Id).FirstOrDefault();
            //Lây danh sách sản phẩm liên quan trong MaTL trong objsanpham
            var lstSanPham = db.SANPHAMs.Where(n => n.MaTL == objSanPham.MaTL).ToList();
            // lấy thông tin sản phẩm theo id nsx
            var objNhaSanXuat = db.NHASANXUATs.Where(n => n.MaNSX == nsx).FirstOrDefault();

            ProductDetail objProductDetail = new ProductDetail();
            objProductDetail.objSanPham = objSanPham;
            objProductDetail.ListSanPham = lstSanPham;
            objProductDetail.objNhaSanXuat = objNhaSanXuat;


            return View(objProductDetail);
        }
    }
}

CypherShop/Views/Cart/Giohang.cshtml
@using CypherShop.Models;
@model List<Cart>
@{
    ViewBag.Title = "Giohang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="width: 80%; max-height: 2000px; margin: 0 auto; background-color: white; border-radius: 10px; margin-top: 20px;">
    <br />
    <h2 style="text-align: center; margin-top: 20px;">THÔNG TIN GIỎ HÀNG</h2>
    <table align="center" border="1" class="table" style="width: 98%; margin: auto; ">
        <tr style="text-align: center; font-weight: bold;">
            <td>Mã Sản Phẩm</td>
            <td>Tên Sản Phẩm</td>
            <td>Ảnh Bìa</td>
            <td>Số Lượng</td>
            <td>Đơn Giá</td>
            <td>Thành Tiền</td>
        </tr>
        @foreach (var item in Model)

        {
            <tr style="text-align: center; font-weight: bold;">
                <td>@item.iMaSP</td>
                <td>@item.sTenSP</td>
                <td><img style="width: 50px; height: 50px;" src="~/Images/@item.sAnhbia" alt="Alternate Text" height="400" width="289" /></td>
                @using (Html.BeginForm("Capnhatgiohang", "Cart", new { @iMasp = item.iMaSP }))
                {
                    <td>
                        <input style="width: 50px; text-align: center; border-radius: 5px;" type="number" name="txtsoluong" value="@item.iSoluong" min="1" />
                    </td>
                    <td>
                        <p style="background-color: #CCFF66; color: black;">@String.Format("{0:0,0}", item.dDongia)đ</p>
                    </td>
                    <td>
                        <p style="background-color: #FFFF00; color: black;">@String.Format("{0:0,0}", item.dThanhtien)đ</p>
                    </td>
                    <td style="width: 90px;">
                        <a style=" text-decoration: none; width: 70px; background-color: #FFCC00; color: white; padding: 5px; border-radius: 5px;" href="@Url.Action("Index","Detail", new{ Id  = item.iMaSP})">Chi Tiết</a>

                    </td>
                    <td>
                        @Html.ActionLink("Xoá", "XoaGioHang", new { @iMasp = item.iMaSP })
                    </td>
                    <td>
                        <input style="border: none; background-color: #00CCFF; color: white; padding: 5px; border-radius: 5px;" type="submit" name="name" value="Cập Nhật" />
                    </td>
                }
            </tr>
        }
        <tr style="text-align: right; font-weight: bold; color: red;">
            <td colspan="4">
                Số Lượng Sản Phẩm: @ViewBag.TongSoLuong
            </td>
            <td colspan="5">
                Tổng Tiền: @String.Format("{0:0,0}", ViewBag.TongTien) VNĐ <br />
                <a href="@Url.Action("Order","Cart")" class="btn btn-primary" style="margin-top: 10px;">Đặt Hàng</a>
            
            </td>
        </tr>
        <tr style="font-weight: bold;text-align: right; color: blue;">
            <td colspan="9">
                @Html.ActionLink("Xoá Giỏ Hàng", "XoaTatCaGioHang")
            </td>
        </tr>

    </table>
    <br />
</div>

CypherShop/Views/Cart/GiohangPartial.cshtml
<a href="@Url.Action("Giohang","Cart")" style="color: white; font-weight: bold; text-decoration: none;">
    <img style="width: 50px; height: 50px;" src="~/Images/cart.png" alt="Alternate Text" /> Giỏ hàng (@ViewBag.TongSoLuong)
</a>

CypherShop/Views/Cart/Order.cshtml
@using CypherShop.Models
@model List<Cart>
@{
    ViewBag.Title = "Đơn Đặt Hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .tvgh a {
        text-decoration: none;
        margin-right: 10px;
    }
</style>
<div style="width: 80%; background-color: white; margin: auto; padding: 20px;">
    <h2 style="text-align: center;">Thông Tin Đơn Đặt Hàng</h2>
    <table align="center" ; border="1" style="width: 99%;">
        <tr style="text-align: center; font-weight: bold;">
            <td style="width: 70px;">Mã Sản Phẩm</td>
            <td>Tên Sản Phẩm</td>
            <td>Ảnh Bìa</td>
            <td style="width: 50px;">Số Lượng</td>
            <td>Đơn Giá</td>
            <td>Thành Tiền</td>
        </tr>
        @foreach (var item in Model)
        {
            <tr style="text-align: center; font-weight: bold;">
                <td>@item.iMaSP</td>
                <td>@item.sTenSP</td>
                <td><img style="width: 50px; height: 50px;" src="~/Images/@item.sAnhbia" alt="Alternate Text" height="400" width="289" /></td>
                @using (Html.BeginForm("Capnhatgiohang", "Cart", new { @iMasp = item.iMaSP }))
                {
                    <td>
                        <p>@item.iSoluong</p>
                    </td>
                    <td>
                        <p style="background-color: #CCFF66; color: black;">@String.Format("{0:0,0}", item.dDongia)đ</p>
                    </td>
                    <td>
                        <p style="background-color: #FFFF00; color: black;">@String.Format("{0:0,0}", item.dThanhtien)đ</p>
                    </td>

                }
            </tr>
        }
        <tr style="font-weight: bold; text-align: right; color: red;">
            <td colspan="3" style="text-align: center;">Số lượng sản phẩm: @ViewBag.Tongsoluong</td>
            <td colspan="3" style="padding-right: 10px;">Tổng Tiền: @String.Format("{0:0,0}", ViewBag.Tongtien)đ</td>
        </tr>
        <tr style="font-weight: bold; text-align: right; color: blue;">
            <td colspan="6" class="tvgh">@Html.ActionLink("Trở Về Giỏ Hàng", "GioHang", "Cart")</td>
        </tr>

    </table>

    <h2 style="text-align: center; margin-top: 20px;">Thông Tin Khách Hàng</h2>
    @{
        KHACHHANG khachhang = (KHACHHANG)Session["users"];
    }
    <table align="center" style="margin-left: 200px;">
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <tr style="height: 40px;">
                <td>Họ tên khách hàng:</td>
                <td style="font-weight: bold;">&ensp;@khachhang.Ho @khachhang.Tenlot @khachhang.Ten</td>
            </tr>
            <tr style="height: 40px;">
                <td>Địa chỉ:</td>
                <td style="font-weight: bold;">@khachhang.DiachiKH</td>
            </tr>
            <tr style="height: 40px;">
                <td>Điện thoại:</td>
                <td style="font-weight: bold;">@khachhang.DienthoaiKH</td>
            </tr>
            <tr style="height: 40px;">
                <td>Ngày đặt:</td>
                <td style="font-weight: bold;">@DateTime.Now.ToShortDateString()</td>
            </tr>
            <tr style="height: 40px;">
                <td>
                    <br />
                    <label>Hình thức thanh toán</label>
                    <br />
                    @Html.DropDownList("MaPhuongThuc")
                    <br />
                    <div id="paypal-button"></div>
                    <br />
                </td>
            </tr>
            <tr style="height: 40px;">
                <td>Ngày giao hàng:</td>
                <td style="font-weight: bold;">
                    <input type="date" name="Ngaygiao" />
                </td>
            </tr>
            <tr style="height: 40px; ">
                <td></td>
                <td>
                    <input style=" margin-left: 150px; margin-top: 10px; width: 200px; height: 40px; color: white; border-radius: 5px; border: none; background-color:#00DD00;" type="submit" value="Đồng Ý Đặt Hàng" />
                </td>
            </tr>
        }
    </table>
</div>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
    paypal.Button.render({
        // Configure environment
        env: 'sandbox',
        client: {
            sandbox: 'AeT1NzfN1hdQR4ZoszcZNCQfw4fcUAbCruCPBB0FZCvtAps7AKbF2qHUdy0gtBojMYkf9AkLPkGVYDug',
            production: 'demo_production_client_id'
        },
        // Customize button (optional)
        locale: 'en_US',
        style: {
            size: 'small',
            color: 'gold',
            shape: 'pill',
        },

        // Enable Pay Now checkout flow (optional)
        commit: true,

        // Set up a payment
        payment: function (data, actions) {
            return actions.payment.create({
                transactions: [{
                    amount: {
                        total: '0.01',
                        currency: 'USD'
                    }
                }]
            });
        },
        // Execute the payment
        onAuthorize: function (data, actions) {
            return actions.payment.execute().then(function () {
                // Show a confirmation message to the buyer
                window.alert('Thank you for your purchase!');
            });
        }
    }, '#paypal-button');

</script>

CypherShop/Views/Cart/Xacnhandonhang.cshtml
@{
    ViewBag.Title = "Xacnhandonhang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="background-color: white; width: 80% ;margin: auto; margin-top: 20px; padding: 20px; border-radius: 10px;">
    <h2 style="text-align: center;">Xác nhận đơn hàng</h2>
    <div style="background-color:#00DD00; width: 80%; height: 140px; margin: auto; padding-left: 50px; padding-top: 10px; border-radius: 10px;">
        <p>- Đơn hàng của bạn đã được đặt thành công ! </p>

        <p>- Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi !</p>
        <p>- Vui lòng chờ thêm ít ngày đễ chúng tôi vận chuyển hàng đến chỗ bạn.</p>
    </div>
    <p style="margin-left: 1050px; margin-top: 20px;">
        @Html.ActionLink("Về Trang Chủ", "Index", "Home")
    </p>

</div>