CypherShop/Models/THELOAI.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CypherShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THELOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THELOAI()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MaTL { get; set; }
        public string TenTheLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}

CypherShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CypherShop.Models;
using PagedList;
using PagedList.Mvc;
namespace CypherShop.Controllers
{
    public class ProductsController : Controller
    {
        CypherShopEntities db = new CypherShopEntities();
        // GET: Products
        public ActionResult Index(int? page)
        {
            if (page == null) page = 1;
            var SANPHAM = (from l in db.SANPHAMs select l).OrderBy(x => x.MaSP);

            int pageSize = 15;

            int pageNumber = (page ?? 1);
            return View(SANPHAM.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Discount()
        {
            int d = 15;
            var lstSanPham = db.SANPHAMs.Where(n => n.Giamgia > d).ToList();
            ProductDetail objProductDetail = new ProductDetail();
            objProductDetail.ListSanPham = lstSanPham;
            return View(objProductDetail);
        }
        public ActionResult TheLoai()
        {
            var lstTheLoai = db.THELOAIs.ToList();
            ProductDetail pr = new ProductDetail();
            pr.ListTheLoai = lstTheLoai;
            return PartialView(pr);
        }
        public ActionResult SPTL(int sp)
        {
            var lstSanPham = db.SANPHAMs.Where(n => n.MaTL == sp).ToList();
            ProductDetail pra = new ProductDetail();
            pra.ListSanPham = lstSanPham;
            return PartialView(pra);
        }
    }
}

CypherShop/Controllers/TheLoaiController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CypherShop.Models;
using PagedList;
using PagedList.Mvc;

namespace CypherShop.Controllers
{
    public class TheLoaiController : Controller
    {
        // GET: TheLoai
        CypherShopEntities db = new CypherShopEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DanhSachTheLoai(int? page)
        {
            if (Session["Taikhoan"] != null)
            {

                int pagesize = 7;
                int pagenum = (page ?? 1);
                return View(db.THELOAIs.ToList().OrderByDescending(n => n.MaTL).ToPagedList(pagenum, pagesize));

            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult DanhSachTheLoai1(int? page)
        {
            if (Session["Taikhoan"] != null)
            {
                int pagesize = 7;
                int pagenum = (page ?? 1);
                return View(db.THELOAIs.ToList().OrderByDescending(n => n.MaTL).ToPagedList(pagenum, pagesize));
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult Timkiem(string SearchString)
        {
            if (Session["Taikhoan"] != null)
            {
                var lstsp = db.THELOAIs.Where(a => a.TenTheLoai.Contains(SearchString)).ToList();
                return View(lstsp);
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }
        public ActionResult Timkiem1(string SearchString)
        {
            if (Session["Taikhoan"] != null)
            {
                var lstsp = db.THELOAIs.Where(a => a.TenTheLoai.Contains(SearchString)).ToList();
                return View(lstsp);
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult XoaTheLoai(int id)
        {
            if (Session["Taikhoan"] != null)
            {
                var sp = db.THELOAIs.Find(id);
                db.THELOAIs.Remove(sp);
                db.SaveChanges();
                return RedirectToAction("DanhSachTheLoai", "TheLoai");
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult XoaTheLoai1(int id)
        {
            if (Session["Taikhoan"] != null)
            {
                var sp = db.THELOAIs.Find(id);
                db.THELOAIs.Remove(sp);
                db.SaveChanges();
                return RedirectToAction("DanhSachTheLoai1", "TheLoai");
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult ThemTheLoai()
        {
            if (Session["Taikhoan"] != null)
            {

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        [HttpPost]
        public ActionResult ThemTheLoai(THELOAI t)
        {

            if (t.TenTheLoai == null)
            {
                Response.Write("<script>alert('Vui lòng nhập tên thể loại')</script>");
                return View();
            }

            else if (db.THELOAIs.Any(x => x.TenTheLoai == t.TenTheLoai))
            {
                Response.Write("<script>alert('Thể loại đã tồn tại')</script>");
                return View();
            }

            else
            {



                db.THELOAIs.Add(t);
                db.SaveChanges();
                Response.Write("<script>alert('Thêm thành công')</script>");
                ModelState.Clear();

                return View();
            }
        }
        public ActionResult ThemTheLoai1()
        {
            if (Session["Taikhoan"] != null)
            {

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        [HttpPost]
        public ActionResult ThemTheLoai1(THELOAI t)
        {

            if (t.TenTheLoai == null)
            {
                Response.Write("<script>alert('Vui lòng nhập tên thể loại')</script>");
                return View();
            }

            else if (db.THELOAIs.Any(x => x.TenTheLoai == t.TenTheLoai))
            {
                Response.Write("<script>alert('Thể loại đã tồn tại')</script>");
                return View();
            }

            else
            {



                db.THELOAIs.Add(t);
                db.SaveChanges();
                Response.Write("<script>alert('Thêm thành công')</script>");
                ModelState.Clear();

                return View();
            }
        }

        public ActionResult CapNhat(int id)
        {
            if (Session["Taikhoan"] != null)
            {

                var sp = db.THELOAIs.Find(id);
                return View(sp);
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        [HttpPost]
        public ActionResult CapNhat(THELOAI t)
        {


            if (t.TenTheLoai == null)
            {
                Response.Write("<script>alert('Vui lòng nhập tên thể loại')</script>");
                return View();
            }
            else if (db.THELOAIs.Any(x => x.TenTheLoai == t.TenTheLoai))
            {
                Response.Write("<script>alert('Thể loại đã tồn tại')</script>");
                return View();
            }


            else
            {

                var update = db.THELOAIs.Find(t.MaTL);
                update.TenTheLoai = t.TenTheLoai;
               



                var id = db.SaveChanges();
                if (id > 0)
                {
                    return RedirectToAction("DanhSachTheLoai");

                }
                else
                {

                    return View(t);
                }
            }
        }

        public ActionResult CapNhat1(int id)
        {
            if (Session["Taikhoan"] != null)
            {

                var sp = db.THELOAIs.Find(id);
                return View(sp);
            }
            else
            {
                return RedirectToAction("Login", "Admin");
            }
        }

        [HttpPost]
        public ActionResult CapNhat1(THELOAI t)
        {


            if (t.TenTheLoai == null)
            {
                Response.Write("<script>alert('Vui lòng nhập tên thể loại')</script>");
                return View();
            }
            else if (db.THELOAIs.Any(x => x.TenTheLoai == t.TenTheLoai))
            {
                Response.Write("<script>alert('Thể loại đã tồn tại')</script>");
                return View();
            }


            else
            {

                var update = db.THELOAIs.Find(t.MaTL);
                update.TenTheLoai = t.TenTheLoai;




                var id = db.SaveChanges();
                if (id > 0)
                {
                    return RedirectToAction("DanhSachTheLoai1");

                }
                else
                {

                    return View(t);
                }
            }
        }

    }
}

CypherShop/Views/Products/Discount.cshtml
@model CypherShop.Models.ProductDetail
@using System.Globalization;
@{
    ViewBag.Title = "Discount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="margin-left: 160px; "><a style="text-decoration: none;" href="@Url.Action("Index","Home")">Trang Chủ</a> / Khuyến Mãi</div>
<div style="width: 80%; margin: auto; margin-top: 10px;">
    <div class="discount-slick" style="margin-left: 10px;">
        <div><img src="~/Images/dkslide1.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide2.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide3.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide4.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide5.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide6.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide7.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide8.jpg" alt="Alternate Text" /></div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('.discount-slick').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: true,
            autoplay: true,
            autoplaySpeed: 3500,
  });
});

</script>
<style>
    .discount-slick .slick-prev {
        margin-left: 40px;
        z-index: 2;
    }

        .discount-slick .slick-prev::before {
            font-size: 40px;
        }

    .discount-slick .slick-next {
        margin-right: 55px;
        z-index: 2;
    }

        .discount-slick .slick-next::before {
            font-size: 40px;
        }
</style>

<div class="discount-products">
    @foreach (var item in Model.ListSanPham)
    {
        <div class="discount-container">
            <a href="@Url.Action("Index","Detail", new { Id = item.MaSP, nsx = item.MaNSX })" style="text-decoration: none;">
                <div class="card discount-product-card">
                    <img class="card-img-top" src="~/Images/@item.Anhbia" alt="Card image" style="width:100%">
                    <div class="card-body">
                        <strong class="card-title discount-card-title">@item.TenSP</strong>
                        <strong class="card-text discount-card-text">@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strong>
                        <div class="clearfix"><strike class="discount-card-gianhap">@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strike><p class="discount-card-km">-@item.Giamgia%</p></div>
                        <strong class="kmk">Khuyến mãi khủng</strong><p href="#" class="btn btn-primary mn">Mua ngay</p>
                    </div>
                </div>
            </a>
        </div>


    }

</div>

CypherShop/Views/Products/Index.cshtml
@using CypherShop.Models
@using PagedList.Mvc
@using System.Globalization;
@model PagedList.PagedList<SANPHAM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="width: 80%; margin: auto; margin-top: 10px;">
    <div class="discount-slick" style="margin-left: 10px;">
        <div><img src="~/Images/dkslide1.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide2.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide3.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide4.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide5.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide6.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide7.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide8.jpg" alt="Alternate Text" /></div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('.discount-slick').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: true,
            autoplay: true,
            autoplaySpeed: 3500,
        });
    });

</script>
<style>
    .discount-slick .slick-prev {
        margin-left: 40px;
        z-index: 2;
    }

        .discount-slick .slick-prev::before {
            font-size: 40px;
        }

    .discount-slick .slick-next {
        margin-right: 55px;
        z-index: 2;
    }

        .discount-slick .slick-next::before {
            font-size: 40px;
        }

    .product-lt {
        width: 80%;
        max-height: 2500px;
        background-color: white;
        border-radius: 10px;
        margin: 0 auto;
    }

    .sanpham-lt {
        width: 300px;
        height: 420px;
        float: left;
        margin-left: 5px;
        margin-top: 5px;
    }
</style>
<div class="product-lt clearfix">
    @Html.Action("TheLoai", "Products")
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Index","Detail", new { Id = item.MaSP, nsx = item.MaNSX })" style="text-decoration: none;font-family: Arial; float: left;">
            <div class="sanpham-lt product_hover">
                <img style="width:100%; height: 58%" src="~/Images/@item.Anhbia" alt="">
                <p class="product_name">@item.TenSP</p>
                <p class="product_detail" style="color: rgb(20, 53, 195) ;"><strong>@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strong>&emsp; &emsp; <img src="~/Images/freeship.svg" alt="Alternate Text" /></p>
                <p class="product_detail" style="margin-top: -15px;"><i class="product_detail_trike_size" style="color: rgb(148, 218, 239); "><strike style="color: dimgrey;">@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strike>&emsp; &emsp;- @item.Giamgia%</i></p>
            </div>
        </a>
    }
</div>
<br />


<div style="color: dodgerblue; margin-left: 750px;">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
</div>
<div class="menutrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>
<style>
    .menutrang {
        padding-top: 20px;
        margin-left: 700px;
    }

        .menutrang li {
            display: inline-block;
        }

            .menutrang li a {
                color: dodgerblue;
                float: left;
                padding: 8px 16px;
                margin-left: 3px;
                text-decoration: none;
                border: 1px solid dodgerblue;
                background-color: white;
            }

            .menutrang li a {
                border-radius: 5px;
            }

                .menutrang li a:hover {
                    background-color: dodgerblue;
                    color: white;
                    border-radius: 5px;
                }
</style>

CypherShop/Views/Products/SPTL.cshtml
@model CypherShop.Models.ProductDetail
@using System.Globalization;
@{
    ViewBag.Title = "SPTL";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width: 80%; margin: auto; margin-top: 10px;">
    <div class="discount-slick" style="margin-left: 10px;">
        <div><img src="~/Images/dkslide1.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide2.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide3.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide4.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide5.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide6.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide7.jpg" alt="Alternate Text" /></div>
        <div><img src="~/Images/dkslide8.jpg" alt="Alternate Text" /></div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('.discount-slick').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            dots: true,
            autoplay: true,
            autoplaySpeed: 3500,
        });
    });

</script>
<style>
    .discount-slick .slick-prev {
        margin-left: 40px;
        z-index: 2;
    }

        .discount-slick .slick-prev::before {
            font-size: 40px;
        }

    .discount-slick .slick-next {
        margin-right: 55px;
        z-index: 2;
    }

        .discount-slick .slick-next::before {
            font-size: 40px;
        }

    .product-lt {
        width: 80%;
        max-height: 2500px;
        background-color: white;
        border-radius: 10px;
        margin: 0 auto;
    }

    .sanpham-lt {
        width: 300px;
        height: 420px;
        float: left;
        margin-left: 5px;
        margin-top: 5px;
    }
</style>
<div class="product-lt clearfix">
    @Html.Action("TheLoai", "Products")
    @foreach (var item in Model.ListSanPham)
    {
        <a href="@Url.Action("Index","Detail", new { Id = item.MaSP, nsx = item.MaNSX })" style="text-decoration: none;font-family: Arial; float: left;">
            <div class="sanpham-lt product_hover">
                <img style="width:100%; height: 58%" src="~/Images/@item.Anhbia" alt="">
                <p class="product_name">@item.TenSP</p>
                <p class="product_detail" style="color: rgb(20, 53, 195) ;"><strong>@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strong>&emsp; &emsp; <img src="~/Images/freeship.svg" alt="Alternate Text" /></p>
                <p class="product_detail" style="margin-top: -15px;"><i class="product_detail_trike_size" style="color: rgb(148, 218, 239); "><strike style="color: dimgrey;">@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strike>&emsp; &emsp;- @item.Giamgia%</i></p>
            </div>
        </a>
    }
</div>

CypherShop/Views/Products/TheLoai.cshtml
@model CypherShop.Models.ProductDetail
<style>
    .product-l li {
        border-bottom: none;
        border-top: none;
    }

        .product-l li a {
            text-decoration: none;
            color: black;
            width: 100%;
            height: 100%;
        }

        .product-l li:hover {
            background-color: #ff3366;
            color: white;
        }

            .product-l li:hover a {
                color: white;
            }
</style>
<div style="float: left; width: 300px; height: 2000px; margin-top: 20px;">
    <ul class="list-group product-l" style="width: 90%; margin: auto;">
        <li class="list-group-item active">Danh Sách Thể Loại</li>
        @foreach (var item in Model.ListTheLoai)
        {
            <li class="list-group-item"><a href="@Url.Action("SPTL", "Products", new { sp = item.MaTL })">@item.TenTheLoai</a></li>


        }

        <li class="list-group-item active">Danh Sách Thể Loại</li>
    </ul>
    </div>