CypherShop/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CypherShop.Controllers
{
    public class BlogsController : Controller
    {
        // GET: Blogs
        public ActionResult Index()
        {
            return View();
        }
    }
}

CypherShop/Controllers/HomeController.cs
using CypherShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using Facebook;
using System.Configuration;

namespace CypherShop.Controllers
{
    public class HomeController : Controller
    {
        CypherShopEntities db = new CypherShopEntities();

        [HttpGet]
        public JsonResult Get()
        {
            return Json("fsdfsdfd", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index(int? page)
        {

            if (page == null) page = 1;
                var SANPHAM = (from l in db.SANPHAMs select l).OrderBy(x => x.MaSP);

                int pageSize = 15;

                int pageNumber = (page ?? 1);
            return View(SANPHAM.ToPagedList(pageNumber, pageSize));
    }
        public ActionResult ProductsCategory()
        {
            var listTheLoai = db.THELOAIs.ToList();
            ProductDetail pro = new ProductDetail();
            pro.ListTheLoai = listTheLoai;
          
            return PartialView(pro);
        }
        public ActionResult Tabpanel()
        {
            var listSanPham = db.SANPHAMs.ToList();

            ProductDetail pro = new ProductDetail();
            pro.ListSanPham = listSanPham;

            return PartialView(pro);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Registrator()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Registrator(KHACHHANG t)
        {
            if (t.Taikhoan == null)
            {
                ModelState.Clear();
                Response.Write("<script>alert('Vui điền tên đăng nhập')</script>");
                return View();
            }

            else if (db.KHACHHANGs.Any(x => x.Taikhoan == t.Taikhoan))
            {
                ModelState.Clear();
                Response.Write("<script>alert('Tài khoản đã tồn tại')</script>");
                return View();
            }
            else if (db.KHACHHANGs.Any(x => x.Email == t.Email))
            {
                ModelState.Clear();
                Response.Write("<script>alert('Email đã được sử dụng')</script>");
                return View();
            }
            else if (t.Matkhau == null)
            {
                ModelState.Clear();
                Response.Write("<script>alert('Vui lòng nhập mật khẩu')</script>");
                return View();
            }
            else if (t.Matkhau.Length < 6)
            {
                ModelState.Clear();
                Response.Write("<script>alert('Mật khẩu từ 6 kí tự trở lên')</script>");
                return View();
            }
            else if (t.NhapLaimatkhau == null)
            {
                ModelState.Clear();
                Response.Write("<script>alert('Vui lòng nhập lại mật khẩu')</script>");
                return View();
            }
            else if (t.Matkhau != t.NhapLaimatkhau)
            {
                ModelState.Clear();
                Response.Write("<script>alert('Vui lòng nhập lại mật khẩu chính xác')</script>");
                return View();
            }
            else if (t.Email == null)
            {
                ModelState.Clear();
                Response.Write("<script>alert('Vui lòng nhập Email')</script>");
                return View();
            }
            else
            {
                db.KHACHHANGs.Add(t);
                db.SaveChanges();
                ModelState.Clear();
                Response.Write("<script>alert('Đăng kí thành công')</script>");
                return View();

            }

        }

        [HttpGet]
        public ActionResult ChangePassword()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
            var lg = db.KHACHHANGs.Where(a => a.Taikhoan.Equals(model.Taikhoan) && a.Matkhau.Equals(model.Matkhaucu)).FirstOrDefault();
            if (lg != null)
            {
                if (model.Matkhaumoi == lg.Matkhau)
                {
                    Response.Write("<script>alert('Mật khẩu mới không được trùng với mật khẩu cũ')</script>");
                    ModelState.Clear();
                    return View();
                }

                else if (model.Matkhaumoi == null)
                {
                    Response.Write("<script>alert('Vui lòng nhập mật khẩu mới')</script>");
                    ModelState.Clear();
                    return View();
                }
                else if (model.Matkhaumoi.Length < 6)
                {
                    Response.Write("<script>alert('Mật khẩu từ 6 kí tự trở lên')</script>");
                    ModelState.Clear();
                    return View();
                }
                else if (model.Matkhaumoi == null)
                {
                    Response.Write("<script>alert('Vui lòng nhập lại mật khẩu mới')</script>");
                    ModelState.Clear();
                    return View();
                }
                else if (model.Matkhaumoi != model.Nhaplaimatkhau)
                {
                    Response.Write("<script>alert('Vui lòng nhập lại chính xác mật khẩu mới')</script>");
                    ModelState.Clear();
                    return View();
                }
                else
                {
                    lg.Matkhau = model.Matkhaumoi;
                    db.SaveChanges();
                    Response.Write("<script>alert('Đổi mật khẩu thành công')</script>");
                    ModelState.Clear();
                    return View();
                }
            }
            else
            {
                Response.Write("<script>alert('Vui lòng nhập đúng tên đăng nhập và mật khẩu')</script>");
                ModelState.Clear();
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(KHACHHANG t)
        {

            var lg = db.KHACHHANGs.Where(a => a.Taikhoan.Equals(t.Taikhoan) && a.Matkhau.Equals(t.Matkhau)).FirstOrDefault();
            if (lg != null)
            {
                Session["users"] = lg;
                Session["user"] = lg.Taikhoan;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Response.Write("<script>alert('Vui lòng kiểm tra tên đăng nhập hoặc mật khẩu')</script>");
                return View();
            }

        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });

            var accessToken = result.access_token;

            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string username = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;


                var user = new KHACHHANG();
                user.Email = email;
                user.Taikhoan = username;
                user.Ho = firstname;
                user.Tenlot = middlename;
                user.Ten = lastname;

                Session["user"] = user.Ho + " " + user.Tenlot + " " + user.Ten;
            }
            else
            {

            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult LogOut()
        {
            Session["user"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Timkiem(string SearchString)
        {
            var lstSanPham = db.SANPHAMs.Where(n => n.TenSP.Contains(SearchString)).ToList();
            return View(lstSanPham);
        }
    }
}
    

CypherShop/Views/Home/ChangePassword.cshtml
@model CypherShop.Models.ChangePasswordModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Đổi mật khẩu</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Usertemp/SignIn/style.css">
</head>
<body>
    <div class="login-wrap">
        <div class="login-html">
            <div class="login-form">
                <div class="sign-in-htm">
                    <form action="#" method="post">
                        <div class="group">
                            <label for="user" class="label"> Tên đăng nhập</label>
                            @*<input id="user" type="text" class="input">*@
                            @Html.EditorFor(model => model.Taikhoan, new { htmlAttributes = new { @id = "user", @type = "text", @class = "input" } })
                        </div>
                        <div class="group">
                            <label for="pass" class="label"> Mật khẩu cũ</label>
                            @*<input id="pass" type="password" class="input">*@
                            @Html.EditorFor(model => model.Matkhaucu, new { htmlAttributes = new { @id = "pass", @type = "password", @class = "input" } })
                        </div>
                        <div class="group">
                            <label for="pass" class="label"> Mật khẩu mới</label>
                            @*<input id="pass" type="password" class="input">*@
                            @Html.EditorFor(model => model.Matkhaumoi, new { htmlAttributes = new { @id = "pass", @type = "password", @class = "input" } })
                        </div>
                        <div class="group">
                            <label for="pass" class="label"> Nhập lại mật khẩu mới</label>
                            @*<input id="pass" type="password" class="input">*@
                            @Html.EditorFor(model => model.Nhaplaimatkhau, new { htmlAttributes = new { @id = "pass", @type = "password", @class = "input" } })
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Đổi mật khẩu">
                        </div>
                        <div class="hr"> </div>
                        <div class="foot-lnk">
                            <a href="Index/Home">Quay lại trang chủ</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>










    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Taikhoan, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Taikhoan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Taikhoan, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Matkhaucu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Matkhaucu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Matkhaucu, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Matkhaumoi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Matkhaumoi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Matkhaumoi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Nhaplaimatkhau, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nhaplaimatkhau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nhaplaimatkhau, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Đổi mật khẩu" class="btn btn-default" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>*@
</body>
</html>

CypherShop/Views/Home/Index.cshtml
@using CypherShop.Models
@using PagedList.Mvc
@using System.Globalization;
@model PagedList.PagedList<SANPHAM>
@{
    ViewBag.Title = "Home Page";
}

<script>/*my slick*/
    $(document).ready(function () {
        $('.slick-ab').slick({
            slidesToShow: 1,
            slidesToScroll: 1,
            infinite: true,
            autoplay: true,
            autoplaySpeed: 3500,
            dots: true,
        });
    });</script>
<style>
    .slick-ab .slick-prev {
        margin-left: 40px;
        z-index: 2;
    }
    .slick-ab .slick-prev::before {
        font-size: 40px;
    }
    .slick-ab .slick-next {
        margin-right: 55px;
        z-index: 2;
    }

        .slick-ab .slick-next::before {
            font-size: 40px;
        }
</style>
<!-- content -->
<div class="content clearfix">

    @Html.Action("Categorys", "Categorys")
    @Html.Action("Slide", "Slide")


    <div class="content_a">
        <a href="@Url.Action("Index","Blogs")"><img style="width: 100%; height:48%; border-radius: 5px;" src="~/Images/tincongnghe.jpg" alt=""></a>
        <img style="width: 100%; height:48%; border-radius: 5px; margin-top: 5%;" src="~/Images/5g.jpg" alt="">
    </div>


</div>

    <div class="client-slider">
        <div class="client-slide-track">
            <div class="client-slide">
                <img src="~/Images/client1.jpg" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client2.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client4.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client3.png" height="100" width="250" alt="" />
            </div><div class="client-slide">
                <img src="~/Images/client5.png" height="100" width="250" alt="" />
            </div>

            <div class="client-slide">
                <img src="~/Images/client6.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client7.jpg" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client1.jpg" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client2.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client4.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client3.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client5.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client6.png" height="100" width="250" alt="" />
            </div>
            <div class="client-slide">
                <img src="~/Images/client7.jpg" height="100" width="250" alt="" />
            </div>

        </div>
    </div>
    <div class="product_hot">
        <div class="product_hot_title">
            <h3 style="float: left; margin-top: 15px;"><strong>|&emsp;Sản Phẩm Bán Chạy</strong> <img style="width: 50px; height: 50px; margin-top: -10px; float: right;" src="~/Images/new.png" alt="Alternate Text" /></h3>
        </div>
        <div class="product_hot_slick">
            @foreach (var item in Model)
            {

                <!-- margin - left: 20px; -->
                <div class="product_hot_slick_hover">
                    <a href="@Url.Action("Index","Detail", new { Id = item.MaSP, nsx = item.MaNSX })" style="text-decoration: none;font-family: Arial; color: black;">
                        <img style="width: 100%; height: 58% ;" src="~/Images/@item.Anhbia" alt=""><img style="width: 40px; height: 40px;" src="~/Images/new.png" alt="Alternate Text" />
                        <div style="width: 300px; height: 200px; ">
                            <p style="width: 255px;overflow: hidden;display: -webkit-box;-webkit-box-orient: vertical;-webkit-line-clamp: 2;">@item.TenSP</p>
                            <p>
                                <b style="color: blue; float: left;"> @string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</b> <img style=" margin-top: 20px; margin-left: 150px;" src="~/Images/freeship.svg" alt="Alternate Text" />
                            </p>
                            <p><strike style="color: dimgrey;">@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strike>&emsp; &emsp;- @item.Giamgia%</p>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>

    <div class="sp_tl">
        @Html.Action("ProductsCategory", "Home")
        @Html.Action("Tabpanel", "Home")
    </div>




    <div class="product_title">
        <h3><strong>|&emsp;Dành Cho Bạn</strong></h3>
    </div>
    <div class="product clearfix">
        @foreach (var item in Model)
        {
            <a href="@Url.Action("Index","Detail", new { Id = item.MaSP, nsx = item.MaNSX })" style="text-decoration: none;font-family: Arial;">
                <div class="sanpham product_hover">
                    <img style="width:100%; height: 58%" src="~/Images/@item.Anhbia" alt="">
                    <p class="product_name">@item.TenSP</p>
                    <p class="product_detail" style="color: rgb(20, 53, 195) ;"><strong>@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strong>&emsp; &emsp; <img src="~/Images/freeship.svg" alt="Alternate Text" /></p>
                    <p class="product_detail" style="margin-top: -15px;"><i class="product_detail_trike_size" style="color: rgb(148, 218, 239); "><strike style="color: dimgrey;">@string.Format(new CultureInfo("vi-VN"), "{0:#,###}", @item.Giaban)đ</strike>&emsp; &emsp;- @item.Giamgia%</i></p>
                </div>
            </a>
        }
    </div>
    <br />


    <div style="color: dodgerblue; margin-left: 750px;">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
    <div class="menutrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
    <style>
        .menutrang {
            padding-top: 20px;
            margin-left: 700px;
        }

            .menutrang li {
                display: inline-block;
            }

                .menutrang li a {
                    color: dodgerblue;
                    float: left;
                    padding: 8px 16px;
                    margin-left: 3px;
                    text-decoration: none;
                    border: 1px solid dodgerblue;
                    background-color: white;
                }

                .menutrang li a {
                    border-radius: 5px;
                }

                    .menutrang li a:hover {
                        background-color: dodgerblue;
                        color: white;
                        border-radius: 5px;
                    }
    </style>

CypherShop/Views/Home/Login.cshtml
@model CypherShop.Models.KHACHHANG

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Usertemp/SignIn/style.css">
</head>
<body>
    <div class="login-wrap">
        <div class="login-html">
            <div class="login-form">
                <div class="sign-in-htm">
                    <form action="#" method="post">
                        <div class="group">
                            <label for="user" class="label"> Tên đăng nhập</label>
                            @*<input id="user" type="text" class="input">*@
                            @Html.EditorFor(model => model.Taikhoan, new { htmlAttributes = new { @id = "user", @type = "text", @class = "input" } })
                        </div>
                        <div class="group">
                            <label for="pass" class="label"> Mật khẩu</label>
                            @*<input id="pass" type="password" class="input">*@
                            @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @id = "pass", @type = "password", @class = "input" } })
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"> <span class="icon"> </span> Nhớ tên đăng nhập</label>
                        </div>
                        <div class="group">
                            <input type="submit" class="button" value="Đăng nhập">
                        </div>
                        <div class="hr"> </div>
                        <div class="foot-lnk">
                            <a href="#forgot"> Quên mật khẩu?</a>
                            <br />
                            <br />
                            <br />
                            @*<a href="#sign-up"> Chưa có tài khoản?</a>*@
                            @Html.ActionLink("Chưa có tài khoản", "Registrator", "Home")
                            <br />
                            <br />
                            @Html.ActionLink("Facebook", "LoginFacebook", "Home")
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @*
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/jqueryval")


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>TAIKHOAN</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Taikhoan1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Taikhoan1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Taikhoan1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Matkhau, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Matkhau, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Matkhau, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NhaplaiMatkhau, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NhaplaiMatkhau, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NhaplaiMatkhau, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

        <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>*@
</body>
</html>

CypherShop/Views/Home/ProductsCategory.cshtml
 @model CypherShop.Models.ProductDetail
    <!-- Nav tabs -->
<ul class="nav" role="tablist">
        <li class="nav-item nav1">
            <a class="nav-link active" data-toggle="tab" href="#home"><strong>Hót Nhất Hôm Nay</strong><br /><p>Ưu đãi hấp dẫn</p></a>
        </li>

    @*<li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu1"><strong>Hàng Mới</strong><br /><p>Ưu đãi đến 28%</p></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu2"><strong>Khuyến Mãi</strong><br /><p>Giảm đến 49%++</p></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu3"><strong>Văn Phòng</strong><br /><p>Giảm đến 20%++</p></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu4"><strong>Học Tập</strong><br /><p>Ưu đãi khủng</p></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu5"><strong>Gaming</strong><br /><p>Giảm đến 35%++</p></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu6"><strong>Coder</strong><br /><p>Quà tặng hấp dẫn</p></a>
        </li>*@
</ul>